import 'dotenv/config'
import { generateText } from 'ai'
import { openai } from '@ai-sdk/openai'
import fs from 'fs'
import { google } from '@ai-sdk/google'



async function salesAnalyst3(account, accountPath, client) {
 
 console.log('🚀 Running Sales Analyst 3')
 console.log(`-- 🛠 Analyzing ${account} \n`)

 // Get financial data
 const salesAnalysis1File = fs.readFileSync(
  `${accountPath}/sales_analysis_1.md`,
  'utf8'
 )
 const jobsAnalysisFile = fs.readFileSync(`${accountPath}/jobs_analysis.md`, 'utf8');

 


 const { text: analysis, usage } = await generateText({
  model: google('gemini-2.0-flash-001'),
  temperature: 0.3,
  system: `You're a sales researcher with decades of experience
You've just joined ${client} to help them with sales research.
 
 Your job is that of a senior sales analyst.
 You will be using insights generated by 2 of your colleagues.
 
 One colleague will send you insights on a target account's financials, 
 trends in this account's industry.
 
 The second colleague will give you insights about the current vendor contracts
 of this account and which ones are expiring soon 
 
 As a senior sales analyst, you are supposed to analyse the insights generated
 by your fellow analysts, and combine them to generate intelligence about
 the target account.
 
 Remember, you will get insights about the areas in which this target account
 is doing well and the areas where they're not doing well from your first 
 colleague.
 
 Use insights about current and expiring vendor contracts to predict what
 existing system improvements can be pitched to the target account

 Here are your detailed instructions:
 
 - Deeply analyse all trends you see and come up with
  * Insights on what might be the next focus areas for this account
  * What existing systems can be modernised based on expiring contracts
  * What net new pitches can be made to this account based on upcoming
	  contracts that are expiring
 - Do not hallucinate.
 - Return the results in Markdown format.
  `,
  prompt: `${account}

  # Company analysis:
  ${salesAnalysis1File}

--------------------------------------

# Jobs:
${jobsAnalysisFile}
 `,
 })

//  console.log('Report usage: ', usage, analysis, '\n ----- \n')
 fs.writeFileSync(`${accountPath}/sales_analysis_3.md`, analysis)

 return analysis

// await new Promise(resolve => setTimeout(resolve, 30000));

}

export default salesAnalyst3
